### ISSUE TITLE
tiling->unsplit from the context menu crashes notion

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#334] opened 2021-04-14 17:39 UTC
```
Apr 14 19:15:11 fukushima systemd-coredump[2607]: Process 1905 (notion) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 1905:
                                                  #0  0x000000000043c9d7 lookup_dynfun (notion + 0x3c9d7)
                                                  #1  0x000000000042465e region_rescue_clientwins (notion + 0x2465e)
                                                  #2  0x0000000000424c6d region_rescue_needed (notion + 0x24c6d)
                                                  #3  0x00007f3dbc8da150 mod_tiling_untile (mod_tiling.so + 0x12150)
                                                  #4  0x00007f3dbc8da21c l2chnd_b_o__WTiling (mod_tiling.so + 0x1221c)
                                                  #5  0x000000000043aa2a extl_l1_call_handler2 (notion + 0x3aa2a)
                                                  #6  0x00007f3dbcccd573 n/a (liblua5.4.so.5 + 0xf573)
                                                  #7  0x00007f3dbccce129 n/a (liblua5.4.so.5 + 0x10129)
                                                  #8  0x00007f3dbcccb6cb n/a (liblua5.4.so.5 + 0xd6cb)
                                                  #9  0x00007f3dbccd039e n/a (liblua5.4.so.5 + 0x1239e)
                                                  #10 0x00007f3dbccd0486 lua_pcallk (liblua5.4.so.5 + 0x12486)
                                                  #11 0x000000000043b505 extl_l1_call_handler (notion + 0x3b505)
                                                  #12 0x00007f3dbcccd573 n/a (liblua5.4.so.5 + 0xf573)
                                                  #13 0x00007f3dbccdceb9 n/a (liblua5.4.so.5 + 0x1eeb9)
                                                  #14 0x00007f3dbccce142 n/a (liblua5.4.so.5 + 0x10142)
                                                  #15 0x00007f3dbcccb6cb n/a (liblua5.4.so.5 + 0xd6cb)
                                                  #16 0x00007f3dbccd039e n/a (liblua5.4.so.5 + 0x1239e)
                                                  #17 0x00007f3dbccd0486 lua_pcallk (liblua5.4.so.5 + 0x12486)
                                                  #18 0x000000000043af8c extl_dodo_call_vararg (notion + 0x3af8c)
                                                  #19 0x000000000043a17c extl_docpcall (notion + 0x3a17c)
                                                  #20 0x00007f3dbcccd573 n/a (liblua5.4.so.5 + 0xf573)
                                                  #21 0x00007f3dbccce129 n/a (liblua5.4.so.5 + 0x10129)
                                                  #22 0x00007f3dbcccb6cb n/a (liblua5.4.so.5 + 0xd6cb)
                                                  #23 0x00007f3dbccd039e n/a (liblua5.4.so.5 + 0x1239e)
                                                  #24 0x00007f3dbccd0486 lua_pcallk (liblua5.4.so.5 + 0x12486)
                                                  #25 0x0000000000439341 extl_cpcall (notion + 0x39341)
                                                  #26 0x000000000043bc81 extl_cpcall_call (notion + 0x3bc81)
                                                  #27 0x000000000043bd66 extl_call (notion + 0x3bd66)
                                                  #28 0x00007f3dbc8fffbf menu_do_finish (mod_menu.so + 0x4fbf)
                                                  #29 0x000000000043765e do_execute (notion + 0x3765e)
                                                  #30 0x000000000041a200 ioncore_mainloop (notion + 0x1a200)
                                                  #31 0x00000000004183dd main (notion + 0x183dd)
                                                  #32 0x00007f3dbc9cab25 __libc_start_main (libc.so.6 + 0x27b25)
                                                  #33 0x000000000041850e _start (notion + 0x1850e)
```

Edit: can anyone reproduce?

**Comment by knixeur** [comment] 2021-07-06 04:14
I didn't catch the stacktrace but I confirm it crashed :(

**Comment by kristopolous** [comment] 2023-02-25 00:31
This is super reproducible and I've been looking into it for a few days. The bug is in ops.c
```
FOR_ALL_MANAGED_BY_TILING(reg, tiling, tmp)
```
That for loop gets corrupted by this line:
```
reg2=group_do_attach(grp, &param, &data); 
```
Which frees the tiling->managed_list object from underneath it and thus corrupts the pointers.

Here's a really reproducible version.  

 1. do rm -fr ~/.notion
 2. start notion in the default tiled mode with 1 application window (such as xterm)
 3. right click on the title bar, go to "Tiling" => "Untile"
 4. enjoy your core.
 
Somehow the reparenting has to be done without the rug pull here. It has been there since *at least* 2014.

**Comment by kristopolous** [comment] 2023-02-27 01:00
back. did the git bisect. defect came in at 8d3f26280c0e3778e48ec33409c884d3f44c99d8, it's the rug pull as theorized. It's in `tiling_managed_remove` right at `splittree_remove`, author is @raboof .

I'll look into it more.

**Comment by raboof** [comment] 2023-02-27 11:49
Ouch, sorry about that. Before https://github.com/raboof/notion/commit/8d3f26280c0e3778e48ec33409c884d3f44c99d8 that splittree_remove was already there, but perhaps triggered under different/fewer conditions. That `if(!reused)` that got removed looks potentially relevant I guess...

> I'll look into it more

Thanks!

**Comment by kristopolous** [comment] 2023-02-28 03:22
it's calling  `ptrlist_remove(&(ws->managed_list), reg);  ` in `tiling_do_managed_remove` which we identified from above as the issue here.

Here's a really cheap solution

```
a/mod_tiling/ops.c b/mod_tiling/ops.c
index 0bd21912..bc5059d9 100644
--- a/mod_tiling/ops.c
+++ b/mod_tiling/ops.c
@@ -147,13 +147,20 @@ bool mod_tiling_untile(WTiling *tiling)
 
         reg2=group_do_attach(grp, &param, &data);
 
+        // See #334: tiling->unsplit from the context menu crashes notion
+        if(tiling->managed_list == NULL) {
+            break;
+        }
+
         if(reg2==NULL)
             warn(TR("Unable to move a region from tiling to group."));
     }
 
     tiling->batchop=FALSE;
 
-    region_dispose((WRegion*)tiling);
+    if(tiling->managed_list != NULL) {
+        region_dispose((WRegion*)tiling);
+    }
 
     return TRUE;
 }
```

we can probably do better than that

**Comment by kristopolous** [comment] 2023-02-28 03:24
I'm also open to just using this and then opening up a more minor memory leak bug which I'm sure is sitting around somewhere in this hack and then just move on.

**Comment by raboof** [comment] 2023-03-21 08:29
I merged #357 - do you want to keep this issue open to keep looking for a clearer solution or rather close it?

**Comment by kristopolous** [comment] 2023-03-23 04:45
no ... let me handle that

**Comment by kristopolous** [comment] 2023-03-23 04:49
apparently only you have the privilege of closing. Feel free to do that now that we have documented and opened up the more major and now less visible issue.

**Closed** 2023-03-23 08:16 UTC
Labels: bug
