### ISSUE TITLE
Strange bug in firefox with styled/custom select widget

### ISSUE THREAD

**Issue by olejorgenb** [raboof/notion#20] opened 2016-06-10 13:03 UTC
Ref: https://github.com/raboof/notion/issues/19 [comment](https://github.com/raboof/notion/issues/19?_pjax=%23js-repo-pjax-container#issuecomment-223934667)

> example: http://ui-grid.info/docs/#/tutorial/103_filtering, scroll down and try to select a gender from the select control in the gender header of the table.

It seems like the mouse coordinates used are offset vertically from the real coordinates. The select list is:

```
<empty>
male
female
unknown
...
```

Clicking on unknown causes female to be selected, clicking female causes male to be selected and so on.
- It works as expected in fullscreen (no tabbar).
- The bug only happens in firefox using notion (tested with i3 and xmonad).
- The bug does not affect the fully native select widget: https://jsfiddle.net/7jp2y4oo/

I spent a few minutes attempting to understand how the UI-grid (or is it a native angular widget?) works, but didn't easily find the interesting parts.

**Comment by molecular** [comment] 2016-06-12 13:39
let me add some comments:

- I'm unsure about what specifics of that ng-grid select make the bug show up at this point
- It works in fullscreen, yes, but only if it's fullscreen on my first screen, not if it's on my secondary screen
- With the select open (box with options is popped up) then right-clicking on some option (opens context-menu) makes subsequent left-clicks work correctly (workaround)

**Comment by raboof** [comment] 2016-06-12 15:56
Indeed I can reproduce this bug on http://ui-grid.info/docs/#/tutorial/103_filterin with Mozilla Iceweasel 44.0.

Interesting observation that opening a context menu makes subsequent left-clicks work correctly.

**Comment by molecular** [comment] 2017-11-28 09:30
My archlinux just updated Firefox to 57.0 and this problem is back ;-(.

It's worse than ever it seems: In the "gender" example linked above, I can't even see any dropdown appearing (I think it's somewhere off-screen) when FF is on my secondary screen. Everything works fine when FF is on my primary screen.

The issue occurs also with some plain <select>s I have (can't show those unfortunately): Sometimes the popup list shows fine, sometimes it's somewhere else in the window (like all the way left), sometimes it appears on the primary screen and sometimes it seems to "appear" off-screen (so: not at all visibly), sometimes I can see a black line (2 pixels high, width about as wide as I would expect the popup to be) on to of the pages rendering area appear.

**Comment by wilhelmy** [comment] 2019-10-27 14:30
Ticket #59 is a duplicate of this, but it is the most active ticket on the issue. Closing this one as duplicate.

**Closed by wilhelmy** 2019-10-27 14:30 UTC
Labels: bug
