### ISSUE TITLE
Firefox right-click menu on wrong screen

### ISSUE THREAD

**Issue by g2boojum** [raboof/notion#57] opened 2017-10-02 19:22 UTC
Recently I started having a problem where the right-click menu in Firefox (version 55 and up) shows up on the wrong screen when using notion, but this doesn't happen when using fluxbox or qtile. It also only happens when firefox is on one screen, but not if it is on the other.

Gentoo system, using either the version of notion in portage (quite old, 2015061300) or directly compiling what is in git (as of 26 Sept 2017, anyway). It doesn't seem to matter if I'm using mod_xinerama and mod_xrandr, or just mod_xrandr. I have two monitors, DisplayPort-0 and DVI-I-0, with DVI-I-0 to the left of DisplayPort-0. Using arandr, it seems that DisplayPort-0 is the primary screen. Putting firefox on DisplayPort-0, the right-click menu ends up on DVI-I-0 to the left. Putting firefox on DVI-I-0, the right-click menu shows up on the DVI-I-0, exactly where one would expect it to show up.

I'm not sure if this is a notion bug, an underlying Xorg bug, or intended behavior that I need to work around. Help? I can't imagine that I've provided enough information to figure out what's going on, but I'm happy to provide feedback if you can give me an idea where to start.

Thanks, and thank you for keeping a very useful WM alive!

**Comment by Veltas** [comment] 2017-10-03 11:11
I also get this, with context menus, and drop-down boxes. However I've seen this before on awesomewm as well. I assume this is a firefox, GTK+, or xrandr bug.

**Comment by louwers** [comment] 2018-05-20 14:37
https://bugzilla.mozilla.org/show_bug.cgi?id=61000

Maybe if we wait another 18 years, this will be fixed.

Most definitely not a notion bug, as it seems to affect people using different window managers, but a fix would be appreciated nonetheless.

**Comment by raboof** [comment] 2018-05-23 16:31
@louwers I'm sure your help would be greatly appreciated... unfortunately it's indeed an unfortunate interaction between not-quite-wrong-not-quite-right behavior across different pieces of software.

At the Notion side I can imagine it has to do with the fact that we introduce the `WScreen` between the root window and the client window, where client coordinates are relative to the `WScreen` rather than to the root window - but because for most window managers those are both at `0x0` sometimes bugs slip in there.

**Comment by wilhelmy** [comment] 2019-10-27 14:29
Ticket #59 is a duplicate of this, but it is the most active ticket on the issue. Closing this one as duplicate.

**Closed by wilhelmy** 2019-10-27 14:29 UTC
